### ISSUE TITLE
Servershell attr command not working

### ISSUE THREAD

**Issue by hasegeli** [innogames/serveradmin#127] opened 2021-01-31 08:40 UTC
I wanted to give Serveradmin a try this weekend.  The new interface looks neat.  Good job!

I added a few attributes, servertypes, and objects.  Object creating went smooth.  Then I realized the "attr" command not working.  Is it a known issue?

I looked at my JavaScript console, but haven't seen anything other than "Failed to load resource: the server responded with a status of 404 (Not Found) http://127.0.0.1:8000/static/js/popper.min.js.map".

This is Safari Version 14.0.2 (16610.3.7.1.9) on MacOS 11.1 here.

**Comment by kofrezo** [comment] 2021-01-31 08:56
Hi Emre,

Thanks 😊. 

The attr command should work. However there are some assumptions (left) which are specific to our configured servertypes and attributes.

I want to clean them up but did not have time yet or a good solution. 

You could try adding the "state" attribute as this has the most hard coded dependencies.

I will check next week what the problem is here. 

Thanks for your report!

**Comment by kofrezo** [comment] 2021-02-01 08:41
Moin Emre,

I just tested it on my local computer. I added a few servertypes and attribute and made them visible via the Servershell attr command (see screenshot). This works for me.

What attributes and servertype do you use ?

**Comment by hasegeli** [comment] 2021-02-01 12:50
I added an attribute typed "relation".  Can you try that?

**Comment by kofrezo** [comment] 2021-02-02 16:29
![Screenshot from 2021-02-02 17-27-37](https://user-images.githubusercontent.com/3993306/106630382-15249080-657c-11eb-8e5b-3e5e134814fe.png)
![Screenshot from 2021-02-02 17-27-52](https://user-images.githubusercontent.com/3993306/106630387-16ee5400-657c-11eb-86f4-02f09f5e7668.png)
![Screenshot from 2021-02-02 17-28-04](https://user-images.githubusercontent.com/3993306/106630399-1950ae00-657c-11eb-8d61-af3ed9f468c8.png)

Works just fine for me. Do you see any difference to your setup ?

**Comment by hasegeli** [comment] 2021-02-07 07:01
I tried exactly the same and the problem remained.  I tried to find out why and noticed that there are two Javascript files named `command.js`.  My browser is probably loading the wrong one.  The problem goes away when I delete `servershell/static/js/servershell/autocomplete/command.js`.

**Comment by kofrezo** [comment] 2021-02-08 09:18
Ah that makes sense.

I split the Javascript files up while the redesign to have an easier time for development. On the long term I wanted to have them merged and minified anyways so there it would not make a difference anymore but until then we could just rename one to a different name.

**Comment by kofrezo** [comment] 2021-02-08 09:30
Can you please check if the linked PR fixes your problem @hasegeli ?

**Comment by hasegeli** [comment] 2021-02-11 16:24
It doesn't fix the problem.  I was wrong.  Though definitely it has something to do with the autocomplete.  The problem goes away when the JavaScript file for autocomplete is removed.

Also, it's worth noting that not only `attr` but none of the commands work on my Safari.  They do work on Chrome.

Can you not reproduce it on Safari?

**Comment by kofrezo** [comment] 2021-02-11 18:00
> Can you not reproduce it on Safari?

We have a few people working with Mac OS but I am unsure if they work with Safari - I will ask them. Otherwise I have a private Mac where I can try to reproduce it (Give me a few days).

> Also, it's worth noting that not only `attr` but none of the commands work on my Safari. They do work on Chrome.

It is at least a bug in terms of design then. Auto completion should not break basic functionality.

**Comment by kofrezo** [comment] 2021-02-19 09:52
Hey @hasegeli,

I can reproduce this now on my Mac.

The problem is with Safari that it seems not properly handle events which we use to update variables such as command, and search term. The command is just always and empty string for Safari because it never changes. I am checking why now. It works on all other Browser though Google Chrome, Opera, Safari, Firefox ...

**Comment by kofrezo** [comment] 2021-02-19 14:23
Okay I found the issue. The problem is that the `change` event is not fired in Safari when the auto completion is enabled. If it is disabled it works just fine.

**Comment by kofrezo** [comment] 2021-02-23 09:41
Hey @hasegeli.

I could not really find out why Safari and other browsers like Epihany do not fire or bubble up the change event for the input if the auto completion is enabled. My Fronted/Javascript knowledge is too limited for this.

However I found a work around that should work. Can you please try it out and let me know if it works for you ?

**Comment by hasegeli** [comment] 2021-02-25 12:31
Yes, it does work.  Thank you.

**Closed** 2021-02-25 12:37 UTC
Labels: bug
